"""Unique Constraints Summarie

Revision ID: 2f92c04d2627
Revises: acfd152dd6aa
Create Date: 2023-02-28 09:31:33.113870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f92c04d2627'
down_revision = 'acfd152dd6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily__summary', schema=None) as batch_op:
        batch_op.drop_index('idx_device_date')
        batch_op.create_unique_constraint('uq_device_date_daily_summary', ['device_id', 'date'])

    with op.batch_alter_table('hourly__summary', schema=None) as batch_op:
        batch_op.drop_index('idx_device_date')
        batch_op.create_unique_constraint('uq_device_date_hourly_summary', ['device_id', 'date'])

    with op.batch_alter_table('monthly__summary', schema=None) as batch_op:
        batch_op.drop_index('idx_device_date')
        batch_op.create_unique_constraint('uq_device_date_monthly_summary', ['device_id', 'month', 'year'])

    with op.batch_alter_table('yearly__summary', schema=None) as batch_op:
        batch_op.drop_index('idx_device_date')
        batch_op.create_unique_constraint('uq_device_date_yearly_summary', ['device_id', 'year'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yearly__summary', schema=None) as batch_op:
        batch_op.drop_constraint('uq_device_date_yearly_summary', type_='unique')
        batch_op.create_index('idx_device_date', ['device_id', 'year'], unique=False)

    with op.batch_alter_table('monthly__summary', schema=None) as batch_op:
        batch_op.drop_constraint('uq_device_date_monthly_summary', type_='unique')
        batch_op.create_index('idx_device_date', ['device_id', 'month', 'year'], unique=False)

    with op.batch_alter_table('hourly__summary', schema=None) as batch_op:
        batch_op.drop_constraint('uq_device_date_hourly_summary', type_='unique')
        batch_op.create_index('idx_device_date', ['device_id', 'date'], unique=False)

    with op.batch_alter_table('daily__summary', schema=None) as batch_op:
        batch_op.drop_constraint('uq_device_date_daily_summary', type_='unique')
        batch_op.create_index('idx_device_date', ['device_id', 'date'], unique=False)

    # ### end Alembic commands ###
